// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Risponde \"status healthy\" sulla root",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "status healthy",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/saluta": {
            "get": {
                "description": "Risponde \"ciao\" o \"ciao {nome}\"",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Saluta il server",
                "responses": {
                    "200": {
                        "description": "ciao\"  \"ciao {nome}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/saluta/con-bestemmia": {
            "get": {
                "description": "Risponde \"Porco Dio\" o \"ciao {nome} che voi Porco Dio\"",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Bestemmia il server",
                "responses": {
                    "200": {
                        "description": "Porco Dio\"  \"ciao {nome} che voi Porco Dio",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API Server Go",
	Description:      "Documentazione API con Swagger",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
