basePath: /
definitions:
  main.LLMRequest:
    properties:
      prompt:
        type: string
    type: object
  main.LLMResponse:
    properties:
      answer:
        type: string
    type: object
  main.NarutoChatRequest:
    properties:
      message:
        type: string
    type: object
  main.NarutoChatResponse:
    properties:
      reply:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Documentazione API con Swagger
  title: API Server Go
  version: "1.0"
paths:
  /:
    get:
      description: Risponde "status healthy" sulla root
      produces:
      - text/plain
      responses:
        "200":
          description: status healthy
          schema:
            type: string
      summary: Health check
      tags:
      - system
  /llm:
    post:
      consumes:
      - application/json
      description: Invia un prompt all'LLM e ritorna la risposta
      parameters:
      - description: Prompt body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.LLMRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.LLMResponse'
      summary: Ask LLM
      tags:
      - llm
  /naruto/chat:
    post:
      consumes:
      - application/json
      description: Cerca su Dattebayo e risponde in italiano pulito via OpenAI
      parameters:
      - description: Messaggio utente
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/main.NarutoChatRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.NarutoChatResponse'
      summary: Chat Naruto (Dattebayo + OpenAI)
      tags:
      - naruto
  /saluta:
    get:
      description: Risponde "ciao" o "ciao {nome}"
      produces:
      - text/plain
      responses:
        "200":
          description: ciao"  "ciao {nome}
          schema:
            type: string
      summary: Saluta il server
      tags:
      - system
  /saluta/con-bestemmia:
    get:
      description: Risponde "Porco Dio" o "ciao {nome} che voi Porco Dio"
      produces:
      - text/plain
      responses:
        "200":
          description: Porco Dio"  "ciao {nome} che voi Porco Dio
          schema:
            type: string
      summary: Bestemmia il server
      tags:
      - system
swagger: "2.0"
